name: Issues
on:
  issues:
    types: [opened, edited]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output github issue details
        run: echo "The event ${{ toJSON(github).event }} triggered this workflow"