name: Issues
on:
  issues:
    types: [opened]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output github issue details
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "The event $GITHUB_CTX.event.issue.title triggered this workflow"